# Generated by Django 4.2.1 on 2023-06-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_specializations_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_id',
        ),
    ]
