# Generated by Django 4.2.1 on 2023-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_registration_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
